name: Python package

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install 'poetry==1.0'
          apt install python3-venv -y
          poetry install
      - name: Lint and test with poetry
        run: |
          poetry run pytest --cov=foliant
          poetry run codecov
          poetry run pylint foliant